server:
  port: 8888
  servlet:
    context-path: /api/v1

security:
  jwt:
    expiration-in-minutes: 30
    secret-key: aG9sYSBtdW5kbyBjb21vIGVzdGFuIGxvcyBzYWx1ZGEgZWwgZXF1aXBvIHNvbHRlY2JvZw==

spring:
  application:
    name: api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    web:
      pageable:
        page-parameter: p
        size-parameter: limit
  h2:
    console:
      enabled: true
      path: /h2-consolas
  jpa:
    # hibernate:
    #   ddl-auto: update
    show-sql: true
#   sql:
#     init:
#       data-locations: classpath:import.sql

logging:
  level:
    root: INFO
    com:
      curso:
        api: DEBUG
    org:
      springframework: INFO
      hibernate: DEBUG